#!/usr/bin/env bash
# Bash script that displays listening ports:
# That only shows listening sockets
# That shows the process id  and name of the program to which each socket belongs

sudo netstat -lp
