#!/usr/bin/env bash
# Configuring the Nginx server to listen port 80.

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
