#!/usr/bin/env bash
# manages "manage my process"
start_process() {
	./manage_my_process &
	echo $! > /var/run/my_process.pid
	echo "manage_my_process started"
}

stop_process() {
	pid=$(cat /var/run/my_process.pid 2>/dev/null)
	if [ -n "$pid" ]; then
		kill $pid
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
	else
		echo "manage_my_process is not running"
	fi
}
restart_process() {
	stop_process
	start_process
	echo "manage_my_process restarted"
}
case "$1" in
    start)
        start_process
        ;;
    stop)
        stop_process
        ;;
    restart)
        restart_process
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac
