#!/usr/bin/env bash
# Displays strings thet indexed from 1 to 100 with the following conditions.
#	"FizzBuzz" if the index is multiple of 3 and 5.
#	"Fizz" if the index is multiple of 3.
#	"Buzz" if the index is multiple of 5.
#	Otherwise, displays the index itself.

for num in {1..100}
do
	if (( num % 3 == 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 == 0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
