#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration,
# it displays "Best School" and then "Hi" on a new line.

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
